# Bangkit Capstone Project : Funders

<table class="tfo-notebook-buttons" align="left">
  <td>
    <a target="_blank" href="https://colab.research.google.com/drive/1bQO_EeCTVFzXa1bOf6JvKjw2f9vkRmQB?usp=sharing"><img src="https://www.tensorflow.org/images/colab_logo_32px.png" />Run in Google Colab</a>
  </td>
  <td>
    <a target="_blank" href="https://github.com/bagussatya/ml-funders/blob/main/Modell/Capstone_Notebook_Prototype.ipynb"><img src="https://www.tensorflow.org/images/GitHub-Mark-32px.png" />View source on GitHub</a>
  </td>
</table>

# Dependencies & Libraries

In [ ]:
#Libraries

import re
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity

#Visualization
import pandas as pd
import json

# Colab library to acces drive
from google.colab import drive

#Data Preprocessing

In [ ]:
#Mounting Drive
drive.mount('/content/gdrive')

Drive already mounted at /content/gdrive; to attempt to forcibly remount, call drive.mount("/content/gdrive", force_remount=True).

In [ ]:
#Cloning Git Repo
username = 'bagussatya'
git_repo = 'ml-funders'
token = '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'

In [ ]:
!git clone  https://{token}@github.com/{username}/{git_repo}.git

Cloning into 'ml-funders'...
remote: Enumerating objects: 26, done.
remote: Counting objects: 100% (26/26), done.
remote: Compressing objects: 100% (7/7), done.
remote: Total 26 (delta 18), reused 25 (delta 17), pack-reused 0
Unpacking objects: 100% (26/26), done.

In [ ]:
%cd {git_repo}/Data/RAW

/content/ml-funders/Data/ml-funders/Data/RAW

In [ ]:
%ls -a

 ./
 ../
'Industri Pengolahan.csv'
'Informasi Dan Komunikasi.csv'
'Jasa Kesehatan Dan Kegiatan Sosial.csv'
'Jasa Keuangan Dan Asuransi.csv'
'Jasa Pendidikan.csv'
'Jasa Perorangan Yg Melayani RT & Keg Yg Menghasilkan Brg & Jasa Oleh RT Yg Digunakan Sendiri Utk Memenuhi Kebutuhan.csv'
'Jasa Persewaan Dan Sewa Guna Usaha Tanpa Hak Opsi, Ketenagakerjaan, Agen Perjalanan Dan Penunjang Usaha Lainnya.csv'
'Jasa Profesional, Ilmiah Dan Teknis.csv'
'Kegiatan Jasa Lainnya.csv'
'Kesenian, Hiburan Dan Rekreasi.csv'
 Konstruksi.csv
'Pengadaan Air, Pengelolaan Sampah Dan Daur Ulang, Pembuangan Dan Pembersihan Limbah Dan Sampah.csv'
'Pengadaan Listrik, Gas, Uap Air Panas Dan Udara Dingin.csv'
'Penyediaan Akomodasi Dan Penyediaan Makan Minum.csv'
'Perdagangan Besar Dan Eceran Reparasi Dan Perawatan Mobil Dan Sepeda Motor.csv'
'Pertambangan Dan Penggalian.csv'
'Pertanian, Kehutanan, Dan Perikanan.csv'
'Transportasi Dan Pergudangan.csv'

## Data Cleaning

In [ ]:
#Load all the data into dataframes

df1 = pd.read_csv('/content/ml-funders/Data/RAW/Industri Pengolahan.csv')
df1.insert(5, 'Kategori', 'Industri Pengolahan')

df2 = pd.read_csv('/content/ml-funders/Data/RAW/Informasi Dan Komunikasi.csv')
df2.insert(5, 'Kategori', 'Informasi Dan Komunikasi')

df3 = pd.read_csv('/content/ml-funders/Data/RAW/Jasa Kesehatan Dan Kegiatan Sosial.csv')
df3.insert(5, 'Kategori', 'Kesehatan Dan Kegiatan Sosial')

df4 = pd.read_csv('/content/ml-funders/Data/RAW/Jasa Keuangan Dan Asuransi.csv')
df4.insert(5, 'Kategori', 'Keuangan Dan Asuransi')

df5 = pd.read_csv('/content/ml-funders/Data/RAW/Jasa Pendidikan.csv')
df5.insert(5, 'Kategori', 'Pendidikan')

df6 = pd.read_csv('/content/ml-funders/Data/RAW/Jasa Perorangan Yg Melayani RT & Keg Yg Menghasilkan Brg & Jasa Oleh RT Yg Digunakan Sendiri Utk Memenuhi Kebutuhan.csv')
df6.insert(5, 'Kategori', 'Jasa Perorangan Yg Melayani RT & Keg Yg Menghasilkan Brg & Jasa Oleh RT Yg Digunakan Sendiri Utk Memenuhi Kebutuhan')

df7 = pd.read_csv('/content/ml-funders/Data/RAW/Jasa Persewaan Dan Sewa Guna Usaha Tanpa Hak Opsi, Ketenagakerjaan, Agen Perjalanan Dan Penunjang Usaha Lainnya.csv')
df7.insert(5, 'Kategori', 'Persewaan Dan Sewa Guna Usaha Tanpa Hak Opsi, Ketenagakerjaan, Agen Perjalanan Dan Penunjang Usaha Lainnya')

df8 = pd.read_csv('/content/ml-funders/Data/RAW/Jasa Profesional, Ilmiah Dan Teknis.csv')
df8.insert(5, 'Kategori', 'Jasa Profesional, Ilmiah Dan Teknis')

df9 = pd.read_csv('/content/ml-funders/Data/RAW/Kegiatan Jasa Lainnya.csv')
df9.insert(5, 'Kategori', 'Kegiatan Jasa Lainnya')

df10 = pd.read_csv('/content/ml-funders/Data/RAW/Kesenian, Hiburan Dan Rekreasi.csv')
df10.insert(5, 'Kategori', 'Kesenian, Hiburan Dan Rekreasi')

df11 = pd.read_csv('/content/ml-funders/Data/RAW/Transportasi Dan Pergudangan.csv')
df11.insert(5, 'Kategori', 'Transportasi Dan Pergudangan')

df12 = pd.read_csv('/content/ml-funders/Data/RAW/Konstruksi.csv')
df12.insert(5, 'Kategori', 'Konstruksi')

df13 = pd.read_csv('/content/ml-funders/Data/RAW/Pengadaan Air, Pengelolaan Sampah Dan Daur Ulang, Pembuangan Dan Pembersihan Limbah Dan Sampah.csv')
df13.insert(5, 'Kategori', 'Pengadaan Air, Pengelolaan Sampah Dan Daur Ulang, Pembuangan Dan Pembersihan Limbah Dan Sampah')

df14 = pd.read_csv('/content/ml-funders/Data/RAW/Pengadaan Listrik, Gas, Uap Air Panas Dan Udara Dingin.csv')
df14.insert(5, 'Kategori', 'Pengadaan Listrik, Gas, Uap Air Panas Dan Udara Dingin')

df15 = pd.read_csv('/content/ml-funders/Data/RAW/Penyediaan Akomodasi Dan Penyediaan Makan Minum.csv')
df15.insert(5, 'Kategori', 'Penyediaan Akomodasi Dan Penyediaan Makan Minum')

df16 = pd.read_csv('/content/ml-funders/Data/RAW/Perdagangan Besar Dan Eceran Reparasi Dan Perawatan Mobil Dan Sepeda Motor.csv')
df16.insert(5, 'Kategori', 'Perdagangan Besar Dan Eceran Reparasi Dan Perawatan Mobil Dan Sepeda Motor')

df17 = pd.read_csv('/content/ml-funders/Data/RAW/Pertambangan Dan Penggalian.csv')
df17.insert(5, 'Kategori', 'Pertambangan Dan Penggalian')

df18 = pd.read_csv('/content/ml-funders/Data/RAW/Pertanian, Kehutanan, Dan Perikanan.csv')
df18.insert(5, 'Kategori', 'Pertanian, Kehutanan, Dan Perikanan')

In [ ]:
#Merge DataFrames

frames = [df1,df2,df3,df4,df5,df6,df7,df8,df9,df10,df11,df12,df13,df14,df15,df16,df17,df18]
data_concat = pd.concat(frames)

In [ ]:
data_concat.head(5)

  web-scraper-order  ... Jumlah Dokumen Persyaratan Kredit
0   1622316592-4811  ...                                 4
1   1622317191-4997  ...                                 4
2   1622316703-4846  ...                               NaN
3   1622315865-4579  ...                                 9
4   1622316184-4680  ...                                 5

[5 rows x 21 columns]

In [ ]:
#Remove NaN or Null Data
data_concat = data_concat.dropna(subset=['Nama']).reset_index()
data_concat = data_concat.drop(data_concat.loc[data_concat['Nama']=='-'].index).reset_index()
data_concat.head(5)

   level_0  ...  Jumlah Dokumen Persyaratan Kredit
0        0  ...                                  4
1        1  ...                                  4
2        2  ...                                  9
3        3  ...                                  5
4        4  ...                                  3

[5 rows x 23 columns]

In [ ]:
#Drop Un-used columns

dropped_columns = ['web-scraper-order', 'web-scraper-start-url', 'Url', 'index', 'level_0']
umkm_df = data_concat.drop(dropped_columns,axis=1)
umkm_df = umkm_df.rename(columns={'Url-href':'URL', 'Total Aset':'Total Aset (Juta)', 'Penjualan Rata-Rata per Tahun':'Penjualan Rata-Rata (Juta/Tahun)',
                                  'Proyeksi Pertumbuhan Penjualan (/tahun)':'Proyeksi Pertumbuhan Penjualan (%/Tahun)','Kebutuhan Pembiayaan Kredit':'Kebutuhan Pembiayaan Kredit (Juta)',
                                  'Nilai Aset yang dapat menjadi jaminan kredit':'Nilai Aset Jaminan Kredit (Juta)'})

In [ ]:
umkm_df.head(5)

                                                 URL  ... Jumlah Dokumen Persyaratan Kredit
0  https://www.bi.go.id/bisaid/bisaid/Detail?pm=/...  ...                                 4
1  https://www.bi.go.id/bisaid/bisaid/Detail?pm=3...  ...                                 4
2  https://www.bi.go.id/bisaid/bisaid/Detail?pm=j...  ...                                 9
3  https://www.bi.go.id/bisaid/bisaid/Detail?pm=b...  ...                                 5
4  https://www.bi.go.id/bisaid/bisaid/Detail?pm=h...  ...                                 3

[5 rows x 18 columns]

In [ ]:
#Cleaning Column Values

df = umkm_df.copy()

#aset
total_aset=[]
for aset in df['Total Aset (Juta)']:
  aset1 = aset.replace('Rp. ','').replace(' Juta','').replace('.','').replace(',','.')
  total_aset.append(aset1)

#penjualan rata-rata
total_penjualan=[]
for aset in df['Penjualan Rata-Rata (Juta/Tahun)']:
  aset1 = aset.replace('Rp. ','').replace(' Juta','').replace('.','').replace(',','.')
  total_penjualan.append(aset1)

#kebutuhan dana
total_kebutuhan=[]
for aset in df['Kebutuhan Pembiayaan Kredit (Juta)']:
  aset1 = aset.replace('Rp. ','').replace(' Juta','').replace('.','').replace(',','.')
  total_kebutuhan.append(aset1)

#jaminan
total_jaminan=[]
for aset in df['Nilai Aset Jaminan Kredit (Juta)']:
  aset1 = aset.replace('Rp. ','').replace(' Juta','').replace('.','').replace(',','.')
  total_jaminan.append(aset1)

#proyeksi
total_proyeksi=[]
for aset in df['Proyeksi Pertumbuhan Penjualan (%/Tahun)']:
  aset1 = aset.replace(' %/Tahun','').replace('-','0')
  total_proyeksi.append(aset1)

#usaha
total_usaha=[]
for aset in df['Usaha Utama']:
  aset1 = aset.replace('Usaha Utama\xa0\xa0: ','')
  total_usaha.append(aset1)

#produk
total_produk=[]
for aset in df['Produk Utama']:
  aset1 = aset.replace('Produk Utama\xa0: ','')
  total_produk.append(aset1)

#provinsi
total_lokasi=[]
prov = 'ACEH|SUMATERA UTARA|SUMATERA BARAT|RIAU|JAMBI|SUMATERA SELATAN|BENGKULU|LAMPUNG|KEPULAUAN BANGKA BELITUNG|KEPULAUAN RIAU|DKI JAKARTA|JAWA BARAT|JAWA TENGAH|DI YOGYAKARTA|JAWA TIMUR|BANTEN|BALI|NUSA TENGGARA BARAT|NUSA TENGGARA TIMUR|KALIMANTAN BARAT|KALIMANTAN TIMUR|KALIMANTAN TENGAH|KALIMANTAN SELATAN|KALIMANTAN UTARA|SULAWESI UTARA|SULAWESI TENGAH|SULAWESI SELATAN|SULAWESI TENGGARA|GORONTALO|SULAWESI BARAT|MALUKU|MALUKU UTARA|PAPUA BARAT|PAPUA'
for aset in df['Alamat']:
  aset1 = re.findall(prov, aset, flags=re.IGNORECASE)
  aset2 = str(aset1[0]).capitalize()
  total_lokasi.append(aset2)

In [ ]:
df['Total Aset (Juta)'] = total_aset
df['Penjualan Rata-Rata (Juta/Tahun)'] = total_penjualan
df['Proyeksi Pertumbuhan Penjualan (%/Tahun)'] = total_proyeksi
df['Kebutuhan Pembiayaan Kredit (Juta)'] = total_kebutuhan
df['Nilai Aset Jaminan Kredit (Juta)'] = total_jaminan
df['Usaha Utama'] = total_usaha
df['Produk Utama'] = total_produk
df.insert(5, 'Provinsi', total_lokasi)

In [ ]:
df.head(5)

                                                 URL  ... Jumlah Dokumen Persyaratan Kredit
0  https://www.bi.go.id/bisaid/bisaid/Detail?pm=/...  ...                                 4
1  https://www.bi.go.id/bisaid/bisaid/Detail?pm=3...  ...                                 4
2  https://www.bi.go.id/bisaid/bisaid/Detail?pm=j...  ...                                 9
3  https://www.bi.go.id/bisaid/bisaid/Detail?pm=b...  ...                                 5
4  https://www.bi.go.id/bisaid/bisaid/Detail?pm=h...  ...                                 3

[5 rows x 19 columns]

In [ ]:
%cd /content/ml-funders/Data

# Output Merged Data
umkm_df.to_csv('Data UMKM.csv',index=False)
# Output Cleaned Data
df.to_csv('Data UMKM Rapi.csv',index=False)

/content/ml-funders/Data

## Data Preparation

In [ ]:
# Function to clean whitespaces in columns values
def clean_data(x):
    if isinstance(x, list):
        return [str.lower(i.replace(" ", "")) for i in x]
    else:
        #Check if director exists. If not, return empty string
        if isinstance(x, str):
            return str.lower(x.replace(" ", ""))
        else:
            return ''

In [ ]:
# Function to soup all the features
def create_soup(x):
    return x['Kategori'] + ' ' + str(x['Kebutuhan Pembiayaan Kredit (Juta)']) + ' ' + str(x['Jumlah Tenaga Kerja']) + ' ' + x['Provinsi']

In [ ]:
# Set the features to merge
features = ['Kategori', 'Kebutuhan Pembiayaan Kredit (Juta)', 'Provinsi']

In [ ]:
# Applying the clean_data function to features
df_train = df.copy()
for feature in features:
    df_train[feature] = df_train[feature].apply(clean_data)

In [ ]:
df_train.head(5)

                                                 URL  ... Jumlah Dokumen Persyaratan Kredit
0  https://www.bi.go.id/bisaid/bisaid/Detail?pm=/...  ...                                 4
1  https://www.bi.go.id/bisaid/bisaid/Detail?pm=3...  ...                                 4
2  https://www.bi.go.id/bisaid/bisaid/Detail?pm=j...  ...                                 9
3  https://www.bi.go.id/bisaid/bisaid/Detail?pm=b...  ...                                 5
4  https://www.bi.go.id/bisaid/bisaid/Detail?pm=h...  ...                                 3

[5 rows x 19 columns]

In [ ]:
features_used = ['Nama','Kategori', 'Kebutuhan Pembiayaan Kredit (Juta)', 'Jumlah Tenaga Kerja', 'Provinsi']
for column in df_train:
  if column not in features_used:
    df_train = df_train.drop(column,axis=1)

In [ ]:
df_train.tail(3)

                          Nama  ... Kebutuhan Pembiayaan Kredit (Juta)
2784  Tuah Bintan Stand Bu Ida  ...                              10.00
2785         Perkebunan Terong  ...                               5.00
2786     Petani Karet Bazrotei  ...                               0.00

[3 rows x 5 columns]

#Getting User Input to calculate similarity

In [ ]:
# Getting User Profile as Input
data = {'Nama':['Investor 1'],
         'Kategori':['Industri Pengolahan'],
         'Provinsi':['DKI Jakarta'],
         'Jumlah Tenaga Kerja':[5.0],
         'Kebutuhan Pembiayaan Kredit (Juta)':[15.0]}
user_df = pd.DataFrame(data)
user_df

         Nama  ... Kebutuhan Pembiayaan Kredit (Juta)
0  Investor 1  ...                               15.0

[1 rows x 5 columns]

In [ ]:
# Appending the user data to item dataframes
df_soup = pd.concat([df_train, user_df]).reset_index()
df_soup

      index  ... Kebutuhan Pembiayaan Kredit (Juta)
0         0  ...                              10.00
1         1  ...                              10.00
2         2  ...                              10.00
3         3  ...                              10.00
4         4  ...                               9.50
...     ...  ...                                ...
2783   2783  ...                               5.00
2784   2784  ...                              10.00
2785   2785  ...                               5.00
2786   2786  ...                               0.00
2787      0  ...                                 15

[2788 rows x 6 columns]

In [ ]:


# Applying the soup function to features
df_soup['soup'] = df_train.apply(create_soup, axis=1)
df_soup['soup']=df_soup['soup'].apply(str)

In [ ]:
df_soup[['soup']].head(2)

                                           soup
0    industripengolahan 10.00 5.0 sumaterautara
1  industripengolahan 10.00 9.0 sulawesiselatan

# Calculating the similarity

In [ ]:
#calculate the similarity

count = CountVectorizer()
count_matrix = count.fit_transform(df_soup['soup'])
cosine_sim2 = cosine_similarity(count_matrix, count_matrix)

In [ ]:
#Getting the index
indices = pd.Series(df_soup.index, index=df_soup['Nama'])

#Getting the 10 most matched with user

In [ ]:
def get_recommendations(user_name, cosine_sim):
    # Get the index of the user_name
    idx = indices[user_name]

    # Get the pairwsie similarity scores
    sim_scores = list(enumerate(cosine_sim[idx]))

    # Sort based on the similarity scores
    sim_scores = sorted(sim_scores, key=lambda x: x[1], reverse=True)

    # Get the scores of the 10 most match items with user
    sim_scores = sim_scores[1:11]

    # Get the item indices
    umkm_indices = [i[0] for i in sim_scores]

    # Return the top 10 most similar items
    return df.iloc[umkm_indices, :]

In [ ]:
result = get_recommendations('Investor 1', cosine_sim2)

In [ ]:
result

                                                 URL  ... Jumlah Dokumen Persyaratan Kredit
0  https://www.bi.go.id/bisaid/bisaid/Detail?pm=/...  ...                                 4
1  https://www.bi.go.id/bisaid/bisaid/Detail?pm=3...  ...                                 4
2  https://www.bi.go.id/bisaid/bisaid/Detail?pm=j...  ...                                 9
3  https://www.bi.go.id/bisaid/bisaid/Detail?pm=b...  ...                                 5
4  https://www.bi.go.id/bisaid/bisaid/Detail?pm=h...  ...                                 3
5  https://www.bi.go.id/bisaid/bisaid/Detail?pm=e...  ...                                 3
6  https://www.bi.go.id/bisaid/bisaid/Detail?pm=X...  ...                                 3
7  https://www.bi.go.id/bisaid/bisaid/Detail?pm=0...  ...                                 4
8  https://www.bi.go.id/bisaid/bisaid/Detail?pm=0...  ...                                 6
9  https://www.bi.go.id/bisaid/bisaid/Detail?pm=K...  ...                                 4

[10 rows x 19 columns]

# Export to JSON

In [ ]:
%cd /content/ml-funders

/content/ml-funders

In [ ]:
json_file = result.to_json('test result.json')